# Generated by Django 5.2.8 on 2025-11-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Movie title', max_length=200)),
                ('year', models.PositiveIntegerField(help_text='Release year')),
                ('genre', models.CharField(blank=True, help_text='Genre (e.g., Action, Comedy)', max_length=100)),
                ('director', models.CharField(blank=True, help_text='Director name', max_length=150)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Your rating (1-5 stars)')),
                ('date_watched', models.DateField(help_text='When you watched it')),
                ('notes', models.TextField(blank=True, help_text='Your thoughts about the movie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-date_watched', '-created_at'],
            },
        ),
    ]
